name: Moviefan
description: Yet another Flutter sample project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flutter_image:
    git: git://github.com/flutter/flutter_image.git
  fluro:
    git: git://github.com/goposse/fluro.git
  redux: ^2.1.1
  flutter_redux: ^0.3.5
  http: ^0.11.3+16
  json_annotation: ^0.2.2
  rxdart: ^0.16.0+1

dev_dependencies:
  build_runner: ^0.7.6
  json_serializable: ^0.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/filterIcon.png

  fonts:
    # https://fonts.google.com/specimen/Kavoon?selection.family=Kavoon
    - family: Kavoon
      fonts:
        - asset: assets/fonts/Kavoon/Kavoon-Regular.ttf
